//package com.makersacademy.acebook.model;
//
//import static org.junit.jupiter.api.Assertions.*;
//
//import com.makersacademy.acebook.model.Comment;
//import org.junit.jupiter.api.Test;
//
//class CommentTest {
//
//    @Test
//    void testCommentCreation() {
//        Comment comment = new Comment("Test content", new Post(), new User());
//        assertNotNull(comment);
//        assertEquals("Test content", comment.getContent());
//    }
//
////    @Test
////    void testCommentIdGeneration() {
////        // Assuming the id is generated by the database
//  }